
  public PromedioPonderado() {
    this.arreglo = new Materia[50];
    this.listaJLabels = new JLabel[50];
    this.indice = 0;
    initComponents();
  }
  
  public void initComponents() {
    final DecimalFormat formato = new DecimalFormat("#.##");
    setTitle("Promedio Ponderado");
    setIconImage(getToolkit().createImage(ClassLoader.getSystemResource("imagenes/icono_promedio.png")));
    setSize(600, 600);
    setResizable(false);
    setLocationRelativeTo((Component)null);
    setDefaultCloseOperation(3);
    JPanel contenedor = new JPanel();
    contenedor.setLayout(new GridBagLayout());
    contenedor.setBackground(Color.white);
    contenedor.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
    GridBagConstraints restriccion = new GridBagConstraints();
    JLabel etq_titulo = new JLabel("CALCULAR PROMEDIO");
    etq_titulo.setFont(new Font("Arial", 1, 35));
    etq_titulo.setForeground(Color.BLACK);
    etq_titulo.setHorizontalAlignment(0);
    restriccion.gridx = 0;
    restriccion.gridy = 0;
    restriccion.gridwidth = 1;
    restriccion.gridheight = 1;
    restriccion.weightx = 100.0D;
    restriccion.weighty = 1.0D;
    restriccion.fill = 1;
    restriccion.insets = new Insets(10, 0, 10, 0);
    contenedor.add(etq_titulo, restriccion);
    restriccion.insets = new Insets(0, 0, 0, 0);
    JPanel panelFormulario = new JPanel();
    panelFormulario.setBackground(new Color(230, 230, 230));
    panelFormulario.setLayout(new GridBagLayout());
    panelFormulario.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
    GridBagConstraints restric = new GridBagConstraints();
    Border borderColor = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.decode("#D5D5D5"));
    Border borderPadding = new EmptyBorder(3, 10, 3, 10);
    Border borderGris = new CompoundBorder(borderColor, borderPadding);
    JLabel etq_materia = new JLabel("Materia:");
    etq_materia.setFont(new Font("Arial", 0, 20));
    etq_materia.setForeground(Color.BLACK);
    etq_materia.setHorizontalAlignment(0);
    restric.gridx = 0;
    restric.gridy = 0;
    restric.gridwidth = 1;
    restric.gridheight = 1;
    restric.weightx = 30.0D;
    restric.weighty = 1.0D;
    restric.fill = 1;
    panelFormulario.add(etq_materia, restric);
    final JTextField campo_materia = new JTextField();
    campo_materia.setColumns(8);
    campo_materia.setFont(new Font("Arial", 0, 18));
    campo_materia.setBorder(borderGris);
    restric.gridx = 1;
    restric.gridy = 0;
    restric.gridwidth = 1;
    restric.gridheight = 1;
    restric.weightx = 20.0D;
    restric.weighty = 1.0D;
    restric.fill = 1;
    panelFormulario.add(campo_materia, restric);
    JLabel etq_creditos = new JLabel("Creditos:");
    etq_creditos.setFont(new Font("Arial", 0, 20));
    etq_creditos.setForeground(Color.BLACK);
    etq_creditos.setHorizontalAlignment(0);
    restric.gridx = 2;
    restric.gridy = 0;
    restric.gridwidth = 1;
    restric.gridheight = 1;
    restric.weightx = 30.0D;
    restric.weighty = 1.0D;
    restric.fill = 1;
    panelFormulario.add(etq_creditos, restric);
    final JTextField campo_creditos = new JTextField();
    campo_creditos.setColumns(8);
    campo_creditos.setFont(new Font("Arial", 0, 18));
    campo_creditos.setBorder(borderGris);
    restric.gridx = 3;
    restric.gridy = 0;
    restric.gridwidth = 1;
    restric.gridheight = 1;
    restric.weightx = 20.0D;
    restric.weighty = 1.0D;
    restric.fill = 1;
    panelFormulario.add(campo_creditos, restric);
    JLabel etq_nota = new JLabel("Nota:");
    etq_nota.setFont(new Font("Arial", 0, 20));
    etq_nota.setForeground(Color.BLACK);
    etq_nota.setHorizontalAlignment(0);
    restric.gridx = 0;
    restric.gridy = 1;
    restric.gridwidth = 1;
    restric.gridheight = 1;
    restric.weightx = 30.0D;
    restric.weighty = 1.0D;
    restric.fill = 1;
    restric.insets = new Insets(5, 0, 5, 0);
    panelFormulario.add(etq_nota, restric);
    final JTextField campo_nota = new JTextField();
    campo_nota.setColumns(8);
    campo_nota.setFont(new Font("Arial", 0, 18));
    campo_nota.setBorder(borderGris);
    restric.gridx = 1;
    restric.gridy = 1;
    restric.gridwidth = 1;
    restric.gridheight = 1;
    restric.weightx = 20.0D;
    restric.weighty = 1.0D;
    restric.fill = 1;
    panelFormulario.add(campo_nota, restric);
    JButton btn_registrar = new JButton("REGISTRAR");
    btn_registrar.setFont(new Font("Arial", 0, 18));
    btn_registrar.setForeground(Color.WHITE);
    btn_registrar.setBackground(new Color(0, 0, 245));
    btn_registrar.setFocusable(false);
    restric.gridx = 2;
    restric.gridy = 1;
    restric.gridwidth = 2;
    restric.gridheight = 1;
    restric.weightx = 50.0D;
    restric.weighty = 1.0D;
    restric.fill = 0;
    panelFormulario.add(btn_registrar, restric);
    restric.insets = new Insets(0, 0, 0, 0);
    restriccion.gridx = 0;
    restriccion.gridy = 1;
    restriccion.gridwidth = 4;
    restriccion.gridheight = 1;
    restriccion.weightx = 100.0D;
    restriccion.weighty = 5.0D;
    restriccion.fill = 2;
    restriccion.anchor = 11;
    contenedor.add(panelFormulario, restriccion);
    
  public PromedioPonderado() {
    this.arreglo = new Materia[50];
    this.listaJLabels = new JLabel[50];
    this.indice = 0;
    initComponents();
  }
  
  public void initComponents() {
    final DecimalFormat formato = new DecimalFormat("#.##");
    setTitle("Promedio Ponderado");
    setIconImage(getToolkit().createImage(ClassLoader.getSystemResource("imagenes/icono_promedio.png")));
    setSize(600, 600);
    setResizable(false);
    setLocationRelativeTo((Component)null);
    setDefaultCloseOperation(3);
    JPanel contenedor = new JPanel();
    contenedor.setLayout(new GridBagLayout());
    contenedor.setBackground(Color.white);
    contenedor.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
    GridBagConstraints restriccion = new GridBagConstraints();
    JLabel etq_titulo = new JLabel("CALCULAR PROMEDIO");
    etq_titulo.setFont(new Font("Arial", 1, 35));
    etq_titulo.setForeground(Color.BLACK);
    etq_titulo.setHorizontalAlignment(0);
    restriccion.gridx = 0;
    restriccion.gridy = 0;
    restriccion.gridwidth = 1;
    restriccion.gridheight = 1;
    restriccion.weightx = 100.0D;
    restriccion.weighty = 1.0D;
    restriccion.fill = 1;
    restriccion.insets = new Insets(10, 0, 10, 0);
    contenedor.add(etq_titulo, restriccion);
    restriccion.insets = new Insets(0, 0, 0, 0);
    JPanel panelFormulario = new JPanel();
    panelFormulario.setBackground(new Color(230, 230, 230));
    panelFormulario.setLayout(new GridBagLayout());
    panelFormulario.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
    GridBagConstraints restric = new GridBagConstraints();
    Border borderColor = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.decode("#D5D5D5"));
    Border borderPadding = new EmptyBorder(3, 10, 3, 10);
    Border borderGris = new CompoundBorder(borderColor, borderPadding);
    JLabel etq_materia = new JLabel("Materia:");
    etq_materia.setFont(new Font("Arial", 0, 20));
    etq_materia.setForeground(Color.BLACK);
    etq_materia.setHorizontalAlignment(0);
    restric.gridx = 0;
    restric.gridy = 0;
    restric.gridwidth = 1;
    restric.gridheight = 1;
    restric.weightx = 30.0D;
    restric.weighty = 1.0D;
    restric.fill = 1;
    panelFormulario.add(etq_materia, restric);
    final JTextField campo_materia = new JTextField();
    campo_materia.setColumns(8);
    campo_materia.setFont(new Font("Arial", 0, 18));
    campo_materia.setBorder(borderGris);
    restric.gridx = 1;
    restric.gridy = 0;
    restric.gridwidth = 1;
    restric.gridheight = 1;
    restric.weightx = 20.0D;
    restric.weighty = 1.0D;
    restric.fill = 1;
    panelFormulario.add(campo_materia, restric);
    JLabel etq_creditos = new JLabel("Creditos:");
    etq_creditos.setFont(new Font("Arial", 0, 20));
    etq_creditos.setForeground(Color.BLACK);
    etq_creditos.setHorizontalAlignment(0);
    restric.gridx = 2;
    restric.gridy = 0;
    restric.gridwidth = 1;
    restric.gridheight = 1;
    restric.weightx = 30.0D;
    restric.weighty = 1.0D;
    restric.fill = 1;
    panelFormulario.add(etq_creditos, restric);
    final JTextField campo_creditos = new JTextField();
    campo_creditos.setColumns(8);
    campo_creditos.setFont(new Font("Arial", 0, 18));
    campo_creditos.setBorder(borderGris);
    restric.gridx = 3;
    restric.gridy = 0;
    restric.gridwidth = 1;
    restric.gridheight = 1;
    restric.weightx = 20.0D;
    restric.weighty = 1.0D;
    restric.fill = 1;
    panelFormulario.add(campo_creditos, restric);
    JLabel etq_nota = new JLabel("Nota:");
    etq_nota.setFont(new Font("Arial", 0, 20));
    etq_nota.setForeground(Color.BLACK);
    etq_nota.setHorizontalAlignment(0);
    restric.gridx = 0;
    restric.gridy = 1;
    restric.gridwidth = 1;
    restric.gridheight = 1;
    restric.weightx = 30.0D;
    restric.weighty = 1.0D;
    restric.fill = 1;
    restric.insets = new Insets(5, 0, 5, 0);
    panelFormulario.add(etq_nota, restric);
    final JTextField campo_nota = new JTextField();
    campo_nota.setColumns(8);
    campo_nota.setFont(new Font("Arial", 0, 18));
    campo_nota.setBorder(borderGris);
    restric.gridx = 1;
    restric.gridy = 1;
    restric.gridwidth = 1;
    restric.gridheight = 1;
    restric.weightx = 20.0D;
    restric.weighty = 1.0D;
    restric.fill = 1;
    panelFormulario.add(campo_nota, restric);
    JButton btn_registrar = new JButton("REGISTRAR");
    btn_registrar.setFont(new Font("Arial", 0, 18));
    btn_registrar.setForeground(Color.WHITE);
    btn_registrar.setBackground(new Color(0, 0, 245));
    btn_registrar.setFocusable(false);
    restric.gridx = 2;
    restric.gridy = 1;
    restric.gridwidth = 2;
    restric.gridheight = 1;
    restric.weightx = 50.0D;
    restric.weighty = 1.0D;
    restric.fill = 0;
    panelFormulario.add(btn_registrar, restric);
    restric.insets = new Insets(0, 0, 0, 0);
    restriccion.gridx = 0;
    restriccion.gridy = 1;
    restriccion.gridwidth = 4;
    restriccion.gridheight = 1;
    restriccion.weightx = 100.0D;
    restriccion.weighty = 5.0D;
    restriccion.fill = 2;
    restriccion.anchor = 11;
    contenedor.add(panelFormulario, restriccion);
    JLabel etq_calcular = new JLabel("RESUMEN");
    etq_calcular.setFont(new Font("Arial", 1, 20));
    etq_calcular.setForeground(Color.BLACK);
    etq_calcular.setHorizontalAlignment(0);
    restriccion.gridx = 0;
    restriccion.gridy = 2;
    restriccion.gridwidth = 4;
    restriccion.gridheight = 1;
    restriccion.weightx = 100.0D;
    restriccion.weighty = 1.0D;
    restriccion.fill = 1;
    restriccion.insets = new Insets(10, 0, 10, 0);
    contenedor.add(etq_calcular, restriccion);
    restriccion.insets = new Insets(0, 0, 0, 0);
    JPanel contenedorItems = new JPanel();
    contenedorItems.setLayout(new GridBagLayout());
    contenedorItems.setBackground(Color.WHITE);
    JScrollPane scrollPane = new JScrollPane(contenedorItems);
    scrollPane.setBorder(borderColor);
    restriccion.gridx = 0;
    restriccion.gridy = 3;
    restriccion.gridwidth = 4;
    restriccion.gridheight = 1;
    restriccion.weightx = 100.0D;
    restriccion.weighty = 90.0D;
    restriccion.fill = 1;
    contenedor.add(scrollPane, restriccion);
    GridBagConstraints constItems = new GridBagConstraints();
    for (int i = 0; i < this.listaJLabels.length; i++) {
      JLabel etq_temporal = new JLabel(" ");
      etq_temporal.setHorizontalAlignment(0);
      etq_temporal.setFont(new Font("Arial", 0, 18));
      etq_temporal.setOpaque(true);
      etq_temporal.setBackground(Color.white);
      etq_temporal.setBorder(borderColor);
      this.listaJLabels[i] = etq_temporal;
      constItems.gridy = i;
      constItems.gridx = 0;
      constItems.gridheight = 1;
      constItems.gridwidth = 1;
      constItems.weighty = 1.0D;
      constItems.weightx = 1.0D;
      constItems.fill = 2;
      constItems.anchor = 11;
      constItems.insets = new Insets(0, 0, 0, 0);
      contenedorItems.add(this.listaJLabels[i], constItems);
    } 
    for (int i = 0; i < this.listaJLabels.length; i++) {
      JLabel etq_temporal = new JLabel(" ");
      etq_temporal.setHorizontalAlignment(0);
      etq_temporal.setFont(new Font("Arial", 0, 18));
      etq_temporal.setOpaque(true);
      etq_temporal.setBackground(Color.white);
      etq_temporal.setBorder(borderColor);
      this.listaJLabels[i] = etq_temporal;
      constItems.gridy = i;
      constItems.gridx = 0;
      constItems.gridheight = 1;
      constItems.gridwidth = 1;
      constItems.weighty = 1.0D;
      constItems.weightx = 1.0D;
      constItems.fill = 2;
      constItems.anchor = 11;
      constItems.insets = new Insets(0, 0, 0, 0);
      contenedorItems.add(this.listaJLabels[i], constItems);
    } 